name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.9
  - aiohttp=3.8.4
  - bokeh=3.2.0
  - dask=2023.7.0
  - dask-labextension=6.1.0
  - holoviews=1.16.2
  - hvplot=0.8.4
  - intake=0.7.0
  - intake-esm=2023.7.7
  - intake-xarray=0.7.0
  - ipywidgets=8.0.7
  - jupyter-server-proxy=4.0.0
  - jupyterhub-singleuser=4.0.1
  - jupyterlab<4
  - jupyterlab_execute_time
  - nbgitpuller =1.1.1
  - netcdf4=1.6.4
  - notebook=6.4.12
  - pip
  - pandas=2.0.3
  - panel=1.2.0
  - param=1.13.0
  - proj=9.2.1 
  - pyproj=3.6.0 
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - statsmodels=0.14.0
  - tqdm=4.65.0
  - wrf-python=1.3.4.1
  - xarray=2023.7.0
  - xclim=0.44.0
  - zarr=2.15.0